# Generated by Django 2.2 on 2020-02-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_vet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='complaint',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
